/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTodosRouteImport } from './routes/app.todos'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppMeIndexRouteImport } from './routes/app.me.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppMeProfileRouteImport } from './routes/app.me.profile'
import { Route as AppMePaymentsRouteImport } from './routes/app.me.payments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppMeProfileRoute = AppMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMePaymentsRoute = AppMePaymentsRouteImport.update({
  id: '/me/payments',
  path: '/me/payments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/todos': typeof AppTodosRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/me/payments': typeof AppMePaymentsRoute
  '/app/me/profile': typeof AppMeProfileRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/me/': typeof AppMeIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/todos': typeof AppTodosRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/me/payments': typeof AppMePaymentsRoute
  '/app/me/profile': typeof AppMeProfileRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/me': typeof AppMeIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/todos': typeof AppTodosRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/me/payments': typeof AppMePaymentsRoute
  '/app/me/profile': typeof AppMeProfileRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/me/': typeof AppMeIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/clients'
    | '/app/employees'
    | '/app/expenses'
    | '/app/todos'
    | '/app/users'
    | '/app/'
    | '/app/me/payments'
    | '/app/me/profile'
    | '/app/projects/$projectId'
    | '/app/me/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/clients'
    | '/app/employees'
    | '/app/expenses'
    | '/app/todos'
    | '/app/users'
    | '/app'
    | '/app/me/payments'
    | '/app/me/profile'
    | '/app/projects/$projectId'
    | '/app/me'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/clients'
    | '/app/employees'
    | '/app/expenses'
    | '/app/todos'
    | '/app/users'
    | '/app/'
    | '/app/me/payments'
    | '/app/me/profile'
    | '/app/projects/$projectId'
    | '/app/me/'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/todos': {
      id: '/app/todos'
      path: '/todos'
      fullPath: '/app/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/': {
      id: '/app/me/'
      path: '/me'
      fullPath: '/app/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/profile': {
      id: '/app/me/profile'
      path: '/me/profile'
      fullPath: '/app/me/profile'
      preLoaderRoute: typeof AppMeProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/payments': {
      id: '/app/me/payments'
      path: '/me/payments'
      fullPath: '/app/me/payments'
      preLoaderRoute: typeof AppMePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppTodosRoute: typeof AppTodosRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMePaymentsRoute: typeof AppMePaymentsRoute
  AppMeProfileRoute: typeof AppMeProfileRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppTodosRoute: AppTodosRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppMePaymentsRoute: AppMePaymentsRoute,
  AppMeProfileRoute: AppMeProfileRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppMeIndexRoute: AppMeIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
